server:
  port: 8080

spring:
  application:
    name: spribe-test-task
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_test_db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

http-client:
  request-timeout: 5s
  idle-connection-wait-time: 30s

fixer:
  url: https://data.fixer.io/api/
  api-key: 92410668d3e4ce8e6b61b0d3d8f5f2a5